language: java
jdk:
  - oraclejdk8
before_script:
  - chmod +x gradlew
script:
  - ./gradlew clean test jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
# skip gradle assemble (skip the install step)
install: true
